### ISSUE TITLE
error in iex

### ISSUE THREAD

**Issue by bigethan** [pcorey/elixir_poster#4]
I'm new to Elixir, but couldn't find any help via googling.  I've got `code` and `image.png` in my directory, but when I follow the README I get:

```
[computer elixir_poster (master)]$ mix deps
* apex 0.3.7 (Hex package) (mix)
  locked at 0.3.7 (apex) 0e4b39ff
  ok
* xml_builder 0.0.9 (Hex package) (mix)
  locked at 0.0.9 (xml_builder) 68f336e8
  ok
* imagineer 0.2.1 (Hex package) (mix)
  locked at 0.2.1 (imagineer) b426707d
  ok
[computer elixir_poster (master)]$ iex -S mix
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ElixirPoster.go

11:20:08.152 [debug] Loading code from './full_elixir_source'...
** (File.Error) could not read file "./full_elixir_source": no such file or directory
           (elixir) lib/file.ex:244: File.read!/1
    (elixir_poster) lib/elixir_poster.ex:51: ElixirPoster.load_code/1
    (elixir_poster) lib/elixir_poster.ex:134: ElixirPoster.go/6
```

Any suggestions would be welcome!

**Comment by pcorey** [comment]
Fixed. It was looking for the source in `full_elixir_source`, not `code`.
