### ISSUE TITLE
Error with the example image?

### ISSUE THREAD

**Issue by Siyfion** [pcorey/elixir_poster#8]
I get the following error when trying to generate with my own code, but the example image mentioned in the README:

```
iex(1)> ElixirPoster.go

12:54:50.071 [debug] Loading code from './code'...

12:54:50.082 [debug] Joining code...

12:54:56.629 [debug] Loading image from './image.png'...

12:54:56.629 [debug] Skipping unknown header cHRM
** (UnicodeConversionError) invalid encoding starting at <<245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, ...>>
    (elixir) lib/list.ex:906: List.to_string/1
    (elixir) lib/enum.ex:1940: Enum."-join/2-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1940: Enum.join/2
    lib/imagineer/image/png/compression/zlib.ex:27: Imagineer.Image.PNG.Compression.Zlib.decompress/1
    lib/imagineer/image/png/compression.ex:14: Imagineer.Image.PNG.Compression.decompress/1
    lib/imagineer/image/png/data_content.ex:12: Imagineer.Image.PNG.DataContent.process/1
    lib/imagineer.ex:27: Imagineer.detect_type_and_process/1
    (elixir_poster) lib/elixir_poster.ex:59: ElixirPoster.load_image/1
```

**Comment by pcorey** [comment]
Hey @Siyfion, not sure what I can do to help other than to tell you that the example image was created with Photoshop as a non-interlaced RGB 8bit PNG. Like the stack trace says, this project is using Imagineer to load images.
